"""initial migration

Revision ID: e71137befa24
Revises: 
Create Date: 2022-06-15 11:50:19.008999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71137befa24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.Date()),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True, default=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
